# Generated by Django 4.0.3 on 2022-03-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.TextField(max_length=100)),
                ('service_description', models.TextField(max_length=200)),
                ('service_price', models.FloatField(blank=True)),
                ('is_static', models.BooleanField(default=True)),
                ('documents', models.FileField(blank=True, upload_to='')),
                ('has_documents', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
                ('type_image', models.ImageField(upload_to='')),
                ('type_description', models.TextField(max_length=200)),
            ],
        ),
    ]
